name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Lint code
        run: yarn lint
      - name: Docker Login with PAT
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_AUTH_TOKEN}}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: stormtuyls/webapp:latest
      - name: Run Docker image
        run: docker run -d -p 3000:3000 stormtuyls/webapp:latest
      - name: Run Tests
        run: yarn test test.spec.js
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: stormtuyls/webapp:latest
          push: true
