name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Lint code
        run: yarn lint
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_AUTH_TOKEN }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: stormtuyls/webapp:latest
          push: true
      - name: Run Tests
        run: yarn test test.spec.js
